### PR TITLE
try: django 2.0

### PR DESCRIPTION
**Pull request by suranig**
Can you upgrade bulma's crispy to django 2.0 and newer? I will be grateful. Good job.

### CODE REVIEW

**Comment by lemonsaurus** [comment]
Seconding this request. @jhotujec

**Comment by heavysaturn** [comment]
..not sure this PR is sufficient, though.

**Comment by JeromeDesseaux** [comment]
Thumbs up! 👍

**Comment by gdude2002** [comment]
It might be worth looking at django-crispy-bulma as a replacement for this project - it's a fork, but it's more active and has already fixed a bunch of stuff.

https://pypi.org/project/django-crispy-bulma/
https://github.com/python-discord/django-crispy-bulma

**Pull request closed without merging**
